### PR TITLE
Player lobby

### PR DESCRIPTION
**Pull request by pillows**
Countdown timer is implemented

Manually tested scenarios

### CODE REVIEW

**Comment by shellyhuang18** [comment]
didn't pull from master first

**Comment by michelleli723** [comment]
start countdown timer is not displaying

**Comment by pillows** [comment]
Added countdown timer that is only shown to game owner.

**Comment by michelleli723** [comment]
Countdown timer works. Button is only shown for the game owner. Timer stops at zero. Game should start after reaching timer reaches zero.

**Pull request merged**
